spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/active_services}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:123456}
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET:nstUwnywnLRwZBHxCOqpxYlA02DRfQt2C0wjIJ4QRFYfdGaMHI}